### ISSUE TITLE
SCUMMVM games does not work in RetroFE when installing Libretro section using libretro_opk_retrofe.opk

### ISSUE THREAD

**Issue by xXS4ALLx** [DrUm78/FunKey-OS#1]
**Describe the bug**
For those just wanting the **Libretro** section in RetroFE and want to play SCUMMVM games by installing the "**libretro_opk_retrofe.opk**" file instead of installing "**FunKey-rootfs-2.3.0-DrUm78.fwu**" firmware update.
SCUMMVM games does not load within RetroFE because of 2 issues.
1. Users are advised to install the cores from the following URL **https://github.com/DrUm78/sdlretro/releases** to the "**FunKey/.sdlretro/cores**" folder on the Funkey. However, this does not include the SCUMMVM core "**scummvm_libretro.so**" file. To resolve this issue, only way to get the SCUMMVM core is by extracting it from the "**scummvm_v2.5.1_funkey-s.opk**" file.
2. As described here **https://github.com/DrUm78/scummvm/releases** on how to setup SCUMMVM games.
Having "**launch.SCUMMVM**" file just boots back to the Libretro Menu in RetroFE, however, if your file is named "**launch.scummvm**" and within the file add an entry of the short game name, the game will boot.

**To Reproduce**
1. Starting fresh: Flash official Funkey OS v2.3.0 "**FunKey-sdcard-2.3.0.img**" file to a a new or existing SD CARD.
2. Install "**libretro_opk_retrofe.opk**".
3. Extract SCUMMVM core file "**scummvm_libretro.so**" from "**scummvm_v2.5.1_funkey-s.opk**" file and place in "**FunKey/.sdlretro/cores**" folder.
4. For purpose of testing, will be using "**Day of the Tentacle**" game.
Copy game to "**Libretro/DOTT**" folder, within the "**DOTT**" folder have file "**launch.SCUMMVM**".
5. In RetroFE/Libretro section, launch game, screen turns black and then boot back into the Libretro section.
6. Rename "**launch.SCUMMVM**" file to "**launch.scummvm**", add entry "**tentacle**" in the "**launch.scummvm**" file.
7. Game boots fine.

If installing "**FunKey-rootfs-2.3.0-DrUm78.fwu**" file, and have "**scummvm_libretro.so**" file in "**FunKey/.sdlretro/cores**" folder. SCUMMVM games will boot fine within RetroFE in Libretro section using dummy "**launch.SCUMMVM**" file.

**Comment by DrUm78** [comment]
1. ScummVM is not included in the SDLRetro essential pack because it's a big core (59 MB) and also because it does require some other dependencies (themes and extra ressources needed for some games like LOL or EOB2 to work)
2. Yes it seems like the empty .SCUMMVM file does not work in RetroFE with the official OS. Maybe it works with my custom OS because I enabled UTF-8 support but that's strange as RetroFE does not support this character coding. 🤔
Anyway I do not support ScummVM for RetroFE because of what I said above and if "tentacle" inside the file works (that's actually the official way to do it according to the [Libretro doc](https://docs.libretro.com/library/scummvm/#running-a-game) but I found it more complex to explain to the users tbh), then there's nothing to fix here.
