### ISSUE TITLE
Building on WSL2 Ubuntu 20.04.06 LTS fails with  _ctypeslib/utils.py : invalid syntax

### ISSUE THREAD

**Issue by hansschmucker** [DrUm78/FunKey-OS#9]
**Describe the bug**
make sdk all fails with error 2. Precise output is
```
2023-07-02T18:17:54 ### Making fun in FunKey
2023-07-02T18:18:01 >>>   Finalizing host directory
2023-07-02T18:18:01 >>>   Finalizing target directory
Done in 4s  (error code: 2)
make: *** [Makefile:58: fun] Error 2
```

**To Reproduce**
1. Install fresh 20.04.06 on WSL2
2. install sdk
3. instal dependencies
4. make sdk all

**Expected behavior**
Build should complete

**Logs**
br.log lists the following details:
```
2023-07-02T18:18:01 rm -rf /home/schmucker/FunKey-OS/FunKey/output/target/usr/lib/luarocks
2023-07-02T18:18:01 PYTHONPATH="/home/schmucker/FunKey-OS/FunKey/output/host/arm-buildroot-linux-musleabihf/sysroot/usr/lib/python2.7/sysconfigdata/" /home/schmucker/FunKey-OS/FunKey/output/host/bin/python2.7 /home/schmucker/FunKey-OS/buildroot/support/scripts/pycompile.py  --strip-root /home/schmucker/FunKey-OS/FunKey/output/target /home/schmucker/FunKey-OS/FunKey/output/target/usr/lib/python2.7
2023-07-02T18:18:02 error:   File "/usr/lib/python2.7/site-packages/pyudev/_ctypeslib/utils.py", line 54
2023-07-02T18:18:02 lib = cdll.LoadLibrary(f'lib{name}.so')
2023-07-02T18:18:02 ^
2023-07-02T18:18:02 SyntaxError: invalid syntax
```

**Additional context**
This is entirely fresh 22.04.06 install. The precise steps before encountering this issue were:

```bash
cd ~
sudo su
apt-get update
apt install bash bc binutils build-essential bzip2 ca-certificates cpio cvs expect file g++ gcc git gzip liblscp-dev libncurses5-dev locales make mercurial openssh-client patch perl procps python python-dev python3 python3-dev python3-distutils python3-setuptools rsync rsync sed subversion sudo tar unzip wget xxd zip
git clone https://github.com/DrUm78/FunKey-OS.git FunKey-OS
wget "https://github.com/FunKey-Project/FunKey-OS/releases/download/FunKey-OS-2.3.0/FunKey-sdk-2.3.0.tar.gz"
tar -xf FunKey-sdk-2.3.0.tar.gz
source $(pwd)/FunKey-sdk-2.3.0/environment-setup
cd FunKey-OS
make sdk all
```

**Comment by hansschmucker** [comment]
Hmmm.
 lib = cdll.LoadLibrary(f'lib{name}.so')
As far as I can tell, this syntax is only available in Python v3... so why does it show up in a directly named 2.7?

**Comment by hansschmucker** [comment]
Can't figure out the version dependency tree here... I'm no good with python.
Just for shits and giggles I've changed the offending line to
```
lib = cdll.LoadLibrary('lib%s.so' % name)
```

... and it seems all is well now, but that really sounds more like a workaround than a solution

**Comment by DrUm78** [comment]
@hansschmucker Can I ask you why you want to compile this branch? It's only for testing and I already pusblished the .fwu and .img files on Discord. I do not provide any support for my test branches.

**Comment by DrUm78** [comment]
@hansschmucker Test version of my custom RG Nano OS with 60 Hz and RTC support (still lacks USB over USB-C though):
IMG file: https://drive.google.com/file/d/1-ETJwMIre0YAFubo6ojEqEEFrAmjTNY0/view?usp=drive_link
FWU file: https://drive.google.com/file/d/1Wx7WHtZBdBpzeUjAGhd57ENxu5fUa49j/view?usp=drive_link
**/!\ IMPORTANT /!\ Please note that the .fwu file is only to update an existing FunKey S card, otherwise please use the .img file to flash either a new card or a RG Nano one (will wipe all data!!).**

**Comment by hansschmucker** [comment]
Honestly because I came here via the GitHub page and it doesn't contain any releases ^^.

Thanks for providing the links. You might want to include this nugget in your README.md as well so that we old-timers have a chance of finding it ;)

Still... it would be great if the source could be built without manual patches... so if you have an idea what's wrong here I'd really appreciate it. It seems to be the only thing missing from a straight-forward build process.

**Comment by DrUm78** [comment]
It does contain releases, but for the FunKey S only so far:
https://github.com/DrUm78/FunKey-OS/releases

The release for the RG Nano is for now a test version as it still lacks the USB-C audio (because Anbernic do not want to share their souce....). But I'm glad I already fixed the compatibility with it and RTC too.

For the Python error, not my fault, but the package one so yes you need to fix it manually. Maybe I will fork it later to implement the fix. Once again, that's only a test branch.

**Comment by hansschmucker** [comment]
Ah, thank you very much for the explanation.

Would be great if you could fork it because other than the missing hint for the previous SDK in the build instruction it's literally the only thing you needed for a clean build process.

Again thanks for your time, effort and the explanation :)

**Comment by DrUm78** [comment]
I deleted the branch on my remote repo for now as I do not want to do any support for it. 👍
